networks:
  app-net:
    driver: bridge

services:
  postgres:
    networks:
      - app-net
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=social-network"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=qwerty12345"
    ports:
      - "5433:5432"

  eureka-server:
    networks:
      - app-net
    build: eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
    ports:
      - "8761:8761"

  user-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - postgres
    build: user-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/social-network
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwerty12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080"

  post-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - postgres
    build: post-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/social-network
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwerty12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080"

  like-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - postgres
    build: like-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/social-network
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwerty12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - "8080"

  api-gateway:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - user-service
      - post-service
      - like-service
    build: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
    ports:
      - "8765:8765"