networks:
  app-net:
    driver: bridge

services:
  postgres:
    networks:
      - app-net
    image: "postgres:latest"
    env_file:
      - .env/postgres.env
    ports:
      - "5433:5432"

  kafka:
    networks:
      - app-net
    image: 'bitnami/kafka:latest'
    container_name: kafka
    env_file:
      - .env/kafka.env
    ports:
      - "9092:9092"
      - "9093:9093"

  eureka-server:
    networks:
      - app-net
    build: eureka-server
    ports:
      - "8761:8761"

  user-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - postgres
    build: user-service
    env_file:
      - .env/eureka-client.env
      - .env/datasource.env
    ports:
      - "8080"

  post-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - postgres
      - kafka
    build: post-service
    env_file:
      - .env/eureka-client.env
      - .env/datasource.env
      - .env/aws-credentials.env
      - .env/kafka-client.env
    ports:
      - "8080"

  like-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - postgres
      - kafka
    build: like-service
    env_file:
      - .env/eureka-client.env
      - .env/datasource.env
      - .env/kafka-client.env
    ports:
      - "8080"

  follow-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - postgres
      - kafka
    build: follow-service
    env_file:
      - .env/eureka-client.env
      - .env/datasource.env
      - .env/kafka-client.env
    ports:
      - "8080"

  api-gateway:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - user-service
      - post-service
      - like-service
      - follow-service
    build: api-gateway
    env_file:
      - .env/eureka-client.env
    ports:
      - "8765:8765"