server:
  port: 0

spring:
  application:
    name: post-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
    username: ${SPRING_DATASOURCE_USERNAME:s333291}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty12345}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

  cloud:
    aws:
      credentials:
        access-key: ${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
        secret-key: ${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      region:
        static: ru-central1
      endpoint: https://storage.yandexcloud.net

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      client-id: "post-service"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

application:
  aws:
    bucket:
      name: killreal777-test-bucket
  kafka:
    topics:
      delete-post: "delete-post"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
