spring:
  application:
    name: USER-DATA-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: a10052004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 25002

eureka:
  client:
    service-url:
      defaultZone : http://localhost:25000/eureka/
