server:
  port: 0

spring:
  application:
    name: translate-service

  cloud:
    openfeign:
      client:
        config:
          yandex-translate:
            defaultRequestHeaders:
              Authorization: Api-Key ${YANDEX.API-KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
