spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user-data-service
          uri: lb://USER-DATA-SERVICE
          predicates:
            - Path=/data/**


server:
  port: 25001

eureka:
  client:
    service-url:
      defaultZone : http://localhost:25000/eureka/